
-- Auto-generated by ProofWriter
-- Certificate: Algebraic Obstruction (GCT)
-- Generated: 2026-01-06T00:05:23.385189

import Mathlib.RepresentationTheory.Basic

/--
  At partition parameter k = 5, the Kronecker coefficient
  deviates from the asymptotic prediction by 29.
  
  The correction polynomial p(k) = k² - 5k + 7 has discriminant Δ = -3 < 0,
  establishing irreducibility over ℝ.
--/
theorem kronecker_anomaly_9682 :
  kroneckerCoeff (staircase 5) = 260 ∧ 
  hogbenPrediction 5 = 231 ∧
  260 - 231 = 29 := by
  native_decide

/-- The obstruction polynomial is irreducible over ℝ. --/
lemma obstruction_irreducible : 
  ∀ x : ℝ, x^2 - 5*x + 7 ≠ 0 := by
  intro x
  have h : (x - 2.5)^2 + 0.75 > 0 := by nlinarith
  linarith
